version: "3.8"
services:
  db_postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres  
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    container_name: db_postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '${PG_ADMIN_PORT}:80'
    depends_on:
      - db_postgres

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=${BACKEND_PORT}
    ports:
      - '${BACKEND_PORT}:3009'
    depends_on:
      - db_postgres
    volumes:
      - ./backend:/usr/src/dist
    env_file:
      - .env